name: cross-rsdpg-128-small
type: signature
claimed-nist-level: 1
length-public-key: 54
length-secret-key: 32
length-signature: 7956
nistkat-sha256: 1ad0ad8138042035f02a38fa69fb10c991dc047b7a14f8144bf2a65c224c1028
testvectors-sha256: daf94941faec14e95b2ace658fea3b7542ea6291f384f861cb09db6ae666bba7
principal-submitters:
  - Marco Baldi
  - Alessandro Barenghi
  - Sebastian Bitzer
  - Patrick Karl
  - Felice Manganiello
  - Alessio Pavoni
  - Gerardo Pelosi
  - Paolo Santini
  - Jonas Schupp
  - Freeman Slaughter
  - Antonia Wachter-Zeh
  - Violetta Weger
implementations:
  - name: clean
    version: 1.2
  - name: avx2
    version: 1.2
    supported_platforms:
      - architecture: x86_64
        required_flags:
          - avx2