name: cross-rsdpg-192-small
type: signature
claimed-nist-level: 3
length-public-key: 83
length-secret-key: 48
length-signature: 18188
nistkat-sha256: 0d30f7c5bb81251ee466973ad1d2691dfb83beaa8afbdebe9dd580923d3ae5d0
testvectors-sha256: 6b401ed19d2a374421ddd36f62591d000a81ef63fc30853c4cb33326fec79990
principal-submitters:
  - Marco Baldi
  - Alessandro Barenghi
  - Sebastian Bitzer
  - Patrick Karl
  - Felice Manganiello
  - Alessio Pavoni
  - Gerardo Pelosi
  - Paolo Santini
  - Jonas Schupp
  - Freeman Slaughter
  - Antonia Wachter-Zeh
  - Violetta Weger
implementations:
  - name: clean
    version: 1.2
  - name: avx2
    version: 1.2
    supported_platforms:
      - architecture: x86_64
        required_flags:
          - avx2